"""update address model to search

Revision ID: 04f6414bf23f
Revises: a4e8fc26d888
Create Date: 2026-05-09 17:16:49.510206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04f6414bf23f'
down_revision = 'a4e8fc26d888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'district', ['district_id'], ['id'])
        batch_op.drop_column('district')
        batch_op.drop_column('description')
        batch_op.drop_column('city')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('district', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('street',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('district_id')

    op.drop_table('district')
    op.drop_table('province')
    # ### end Alembic commands ###
