"""update transaction model

Revision ID: 9009e98e5ec8
Revises: 988166d2024d
Create Date: 2026-05-19 14:33:14.134162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9009e98e5ec8'
down_revision = '988166d2024d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('app_trans_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('payment_url',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['app_trans_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('payment_url',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('app_trans_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
